---
# tasks file for setup crond
- name: ensure cron daemon is enabled
  service:
    name: crond
    state: started
    enabled: yes

- name: ensure permissions on /etc/crontab are configured
  file:
    path: /etc/crontab
    owner: root
    group: root
    mode: '0600'

- name: ensure permissions on /etc/cron.* are configured
  file:
    path: "/etc/cron.{{ item }}"
    owner: root
    group: root
    mode: '0700'
  loop:
    - hourly
    - daily
    - weekly
    - monthly
    - d

- name: ensure at/cron deny file doesnt exist
  file:
    path: /etc/{{ item }}.deny
    state: absent
  loop:
    - at
    - cron

- name: ensure at/cron allow file exist
  template:
    src: cron.allow.j2
    dest: /etc/{{ item }}.allow
    owner: root
    group: root
    mode: '0600'
  loop:
    - at
    - cron